### ISSUE TITLE
Error when applying to media player in status "off"

### ISSUE THREAD

**Issue by cicero200272** [NinDTendo/homeassistant_gradual_volume_control#1]
Hi,

First of all I'd like to say "thank you" for this useful component! I had a workaround with several "volume_set" and "delay" commands in a sequence which I can ditch now in favour of this component.

Nevertheless I remarked that the component throws an exception when I try to apply `grad_vol.set_volume` to a media player in status "off" (since it does not hold an attribute `volume_level` I suppose)...

Would be nice if the component could catch this exception and just ignore media players w/o volume_level.

Cheers,
Tim

> websocket_api script: Error executing script. Unexpected error for call_service at pos 1: float() argument must be a string or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2013, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/grad_vol/__init__.py", line 13, in handle_set_volume
    volume = round(float(hass.states.get(entity_id).attributes.get('volume_level')),2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'

**Comment by NinDTendo** [comment]
Hi,
thanks for the feedback.
I made a temporary fix, basically ignoring 'off' entities.
